/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './index.tsx',
    './App.tsx',
    './constants.tsx',
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        ink: '#0A0A0B',
        background: '#0A0A0B',
        panel: '#131316',
        section: '#0F0F11',
        cards: '#131316',
        raised: '#17171A',
        frame: '#141417',
        wire: '#7C74FF',
        wireDim: '#4B4877',
        signal: '#7C74FF',
        signalDim: '#635BF7',
        primary: '#7C74FF',
        secondary: '#A78BFA',
        accent: '#7C74FF',
        success: '#22C55E',
        glass: 'rgba(19, 19, 22, 0.72)',
        border: 'rgba(255, 255, 255, 0.09)',
        text: '#FAFAFA',
        textSecondary: '#A1A1AA',
        muted: '#71717A',
      },
      fontFamily: {
        sans: ['Sora', 'system-ui', 'sans-serif'],
        display: ['Space Grotesk', 'Sora', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      letterSpacing: { tightest: '-0.045em' },
      maxWidth: { shell: '1240px' },
      spacing: { 13: '3.25rem' },
    },
  },
  plugins: [],
};
