/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './index.tsx',
    './App.tsx',
    './constants.tsx',
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        ink: '#F6F6F3',
        background: '#F6F6F3',
        panel: '#FFFFFF',
        section: '#FFFFFF',
        cards: '#FFFFFF',
        raised: '#FFFFFF',
        frame: '#EFEFEA',
        wire: '#5B4BF5',
        wireDim: '#A5A2F5',
        signal: '#5B4BF5',
        signalDim: '#4F46E5',
        primary: '#5B4BF5',
        secondary: '#8B5CF6',
        accent: '#5B4BF5',
        success: '#16A34A',
        glass: 'rgba(255, 255, 255, 0.72)',
        border: 'rgba(17, 17, 34, 0.10)',
        text: '#0D0D12',
        textSecondary: '#52525E',
        muted: '#6E6E78',
      },
      fontFamily: {
        sans: ['Sora', 'system-ui', 'sans-serif'],
        display: ['Space Grotesk', 'Sora', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      letterSpacing: { tightest: '-0.045em' },
      maxWidth: { shell: '1240px' },
      spacing: { 13: '3.25rem' },
    },
  },
  plugins: [],
};
