import React from 'react';
import SectionHeading from './ui/SectionHeading';
import Reveal from './ui/Reveal';

const ACHIEVEMENTS = [
  'Built and deployed four AI-powered products end to end, solo — design, backend, prompts, deploy.',
  'Scaled Photo Resizer past a million users as the go-to tool for Indian government exam photo rules, at zero server cost by keeping every byte client-side.',
  'Indexed 200+ AI tools across 10 categories on AI Master Tools, with the SEO pages generated by a pipeline rather than by hand.',
  'Cut content production time by more than 60% for clients by handing the repetitive stages to agents and keeping humans on the judgement calls.',
  'Designed multimodal prompt systems — text, image, audio, video — that run inside production SaaS rather than in a playground.',
  'Delivered full AI infrastructure for agency clients: model layer, database layer and automation pipelines wired together and documented.',
];

const Achievements: React.FC = () => (
  <section className="relative py-24 md:py-32">
    <div className="container mx-auto max-w-shell px-6">
      <SectionHeading
        eyebrow="Track record"
        title="Six things worth pointing at"
        className="mb-14"
      />

      <ol className="grid gap-px overflow-hidden rounded-2xl border border-border bg-[rgba(150,155,180,0.16)] md:grid-cols-2">
        {ACHIEVEMENTS.map((item, i) => (
          <li key={i} className="bg-panel">
            <Reveal delay={(i % 2) * 0.06}>
              <div className="group flex h-full gap-5 p-7 transition-colors hover:bg-cards">
                <span className="font-mono text-[12px] text-wire/70 transition-colors group-hover:text-wire">
                  {String(i + 1).padStart(2, '0')}
                </span>
                <p className="text-[15px] leading-relaxed text-textSecondary transition-colors group-hover:text-text">
                  {item}
                </p>
              </div>
            </Reveal>
          </li>
        ))}
      </ol>
    </div>
  </section>
);

export default Achievements;
