import React from 'react';
import SectionHeading from './ui/SectionHeading';
import Reveal from './ui/Reveal';

// Every line here has to survive "how do you know?" from an interviewer. The
// set this replaced said four products where the rest of the site says five,
// 200 tools where the directory lists 650, and claimed a 60% saving "for
// clients" and infrastructure "for agency clients" that nothing could back.
const ACHIEVEMENTS = [
  'Built and deployed five web products end to end, solo — design, front end, prompts, deploy.',
  'Built Photo Resizer to run entirely in the browser for Indian government exam photo rules — no upload, no account, and no server bill.',
  'Put 650+ AI tools on AI Master Tools, with every SEO page generated by a pipeline rather than written by hand.',
  'Generated a 13-workflow business intelligence system from source code instead of the n8n editor, behind a 190+ check suite that runs before every deploy.',
  'Held a 10-stage content pipeline to a strict JSON schema at every step, with a quality gate and a hard block on stating unverified figures as fact.',
  'Traced a ranking collapse to its real cause — a frozen sitemap date that stopped recrawling for 20 days — instead of the obvious, wrong culprit.',
];

const Achievements: React.FC = () => (
  <section className="relative py-24 md:py-32">
    <div className="container mx-auto max-w-shell px-6">
      <SectionHeading
        eyebrow="Track record"
        title="Six things worth pointing at"
        className="mb-14"
      />

      <ol className="grid gap-px overflow-hidden rounded-2xl border border-border bg-[rgba(150,155,180,0.16)] md:grid-cols-2">
        {ACHIEVEMENTS.map((item, i) => (
          <li key={i} className="bg-panel">
            <Reveal delay={(i % 2) * 0.06}>
              <div className="group flex h-full gap-5 p-7 transition-colors hover:bg-cards">
                <span className="font-mono text-[12px] text-wire/70 transition-colors group-hover:text-wire">
                  {String(i + 1).padStart(2, '0')}
                </span>
                <p className="text-[15px] leading-relaxed text-textSecondary transition-colors group-hover:text-text">
                  {item}
                </p>
              </div>
            </Reveal>
          </li>
        ))}
      </ol>
    </div>
  </section>
);

export default Achievements;
